# Gobelins
[[enemies]]
type = "Gobelin"
rank = "Named"
names = ["Gribz", "Zug", "Snark", "Grobnar", "Blix", "Druk", "Rikrik", "Glim", "Zoz", "Nark"]

[[enemies]]
type = "Gobelin"
rank = "Elite"
names = ["Grum le Cruel", "Zkro le Methodiste", "Thrag le Brutal", "Makgorah l'Invaincu"]

[[enemies]]
type = "Gobelin"
rank = "Boss"
names = ["Skarn le Destructeur", "Gorath l'ancien"]

[[enemies]]
type = "Gobelin"
rank = "Legendary"
names = ["Gnorlax le père de toute choses", "Gshlomog la main d'or"]

#Skeleton
[[enemies]]
type = "Skeleton"
rank = "Named"
names = ["Osram", "Clatter", "Drybone", "Rattle", "Marrow", "Skorn", "Bonelord", "Grimjaw", "Skarn", "Femur"]

[[enemies]]
type = "Skeleton"
rank = "Elite"
names = ["Seigneur Fémur", "Capitaine Tibia", "Karg l’Osseux", "Morbius"]

[[enemies]]
type = "Skeleton"
rank = "Boss"
names = ["Archiliche Noctis"]

[[enemies]]
type = "Skeleton"
rank = "Legendary"
names = ["Le Roi-Liche Eternel"]

#Human
[[enemies]]
type = "Human"
rank = "Named"
names = ["Silas", "Nyra", "Vex", "Kael", "Shade", "Lira", "Raze", "Dorin", "Thorne", "Nim"]

[[enemies]]
type = "Human"
rank = "Elite"
names = ["Valtor l’Ombre", "Sir Garrick", "Erik le Fourbe", "Kaelen le Vif"]

[[enemies]]
type = "Human"
rank = "Boss"
names = ["Commandant Draven", "Capitaine Valerius"]

[[enemies]]
type = "Human"
rank = "Legendary"
names = ["L’Empereur Noir"]

# Orc
[[enemies]]
type = "Orc"
rank = "Named"
names = ["Gorbag", "Uzgakh", "Murz", "Thok", "Drog", "Krag", "Urbul", "Nazg", "Grush", "Bolg"]

[[enemies]]
type = "Orc"
rank = "Elite"
names = ["Throm le Ravageur", "Kharz le Briseur", "Urgol le Sanguinaire"]

[[enemies]]
type = "Orc"
rank = "Boss"
names = ["Gorthak Brise-Monde"]

[[enemies]]
type = "Orc"
rank = "Legendary"
names = ["Zodd l'immortel", "Ymn'osh le Jaune"]

# Demon
[[enemies]]
type = "Demon"
rank = "Named"
names = ["Azrak", "Malikar", "Vorin", "Ghaz", "Xeroth"]

[[enemies]]
type = "Demon"
rank = "Elite"
names = ["Zariel le Fléau", "Belkor le Dévoreur"]

[[enemies]]
type = "Demon"
rank = "Boss"
names = ["Archidémon Ragath", "Belial le Roi des Démons"]

[[enemies]]
type = "Demon"
rank = "Legendary"
names = ["Eve la Séductrice", "???"]

# Vampire
[[enemies]]
type = "Vampire"
rank = "Named"
names = ["Seraphine", "Valen", "Mordred", "Lilith", "Cassian", "Isolde", "Lucian", "Dorian", "Selene", "Alaric"]

[[enemies]]
type = "Vampire"
rank = "Elite"
names = ["Comtesse Vespera", "Malachar le Déshérité", "Baroness Nyx", "Duc Thorne"]

[[enemies]]
type = "Vampire"
rank = "Boss"
names = ["Seigneur Vladis", "Dame Morgana"]

[[enemies]]
type = "Vampire"
rank = "Legendary"
names = ["Vladd l'Empaleur", "Sunev l'Éternelle"]