# ---------------------------------------------
# 3) SPAWN RATES (poids) â€” facultatif
#    retombe sur DEFAULT_RATES si absent
# ---------------------------------------------
[spawn_rates.default_non_boss]
lambda = 60
named = 30
elite = 10

[spawn_rates.default_boss]
boss = 97
legendary = 3